carts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
]

store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search'),

]

toyland/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('store.urls')),
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
from django.db import models
from store.models import Product,Variation
# Create your models here.
class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)


    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart    = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)


    def sub_total(self):
        return self.product.price * self.quantity

    def __unicode__(self):
        return self.product

store/models.py
from django.db import models
from category.models import Category
from django.urls import reverse



# Create your models here.
class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug         =models.SlugField(max_length=200, unique=True)
    description  =models.TextField(max_length=500, blank=True)
    price        = models.IntegerField()
    images       = models.ImageField(upload_to = 'photos/products')
    stock        = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category     =models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add = True)
    modified_date = models.DateTimeField(auto_now=True)


    def get_url(self):
        return reverse('product_detail', args=[self.category.slug, self.slug])


    def __str__(self):
        return self.product_name

class VariationManager(models.Manager):
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)


variation_category_choice = (
            ('color', 'color'),

)

class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choice)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now=True)


    objects = VariationManager()
    def __str__(self):
        return self.variation_value

carts/views.py
from django.shortcuts import render, get_object_or_404
from store.models import Product, Variation
from .models import Cart,CartItem
from django.shortcuts import redirect
from django.http import HttpResponse
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    product_variation = []

    if request.method == 'POST':
        for key, value in request.POST.items():
            try:
                variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                product_variation.append(variation)
            except Variation.DoesNotExist:
                pass

    cart_id = _cart_id(request)
    cart, created = Cart.objects.get_or_create(cart_id=cart_id)

    is_cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()

    if is_cart_item_exists:
        cart_item = CartItem.objects.filter(product=product, cart=cart)

        ex_var_list = [list(item.variations.all()) for item in cart_item]

        if product_variation in ex_var_list:
            index = ex_var_list.index(product_variation)
            item_id = cart_item[index].id
            item = CartItem.objects.get(product=product, id=item_id)
            item.quantity += 1
            item.save()
        else:
            item = CartItem.objects.create(product=product, quantity=1, cart=cart)
            if product_variation:
                item.variations.clear()
                item.variations.add(*product_variation)
            item.save()
    else:
        cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
        if product_variation:
            cart_item.variations.clear()
            cart_item.variations.add(*product_variation)
        cart_item.save()

    return redirect('cart')

def remove_cart(request, product_id, cart_item_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity >1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.on_delete()
    except:
        pass
    return redirect('cart')

def remove_cart_item(request, product_id,cart_item_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id =product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect('cart')




def cart(request,total=0,quantity=0,cart_items=None):
    try:
        tax = 0
        grand_total = 0
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (2 * total)/100
        grand_total =  total + tax
    except ObjectDoesNotExist:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total' : grand_total,
    }
    return render(request, 'store/cart.html', context)

store/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product
from category.models import Category
from carts.views import _cart_id
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponse
from carts.models import CartItem
from django.db.models import Q







def store(request, category_slug=None):
    categories = None
    products = None
    product_count = None

    if category_slug != None:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=categories, is_available=True)
        paginator = Paginator(products, 9)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()
    else:
        products = Product.objects.all().filter(is_available=True).order_by('id')
        paginator = Paginator(products, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()

    context = {
        'products': paged_products,
        'product_count': product_count,
    }
    return render(request, 'store/store.html', context)


def product_detail(request, category_slug, product_slug):
    try:
        single_product = Product.objects.get(category__slug=category_slug, slug=product_slug)
        in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(request), product=single_product).exists()

    except Exception as e:
        raise e

    context = {
            'single_product': single_product,
            'in_cart': in_cart,
    }

    return render(request, 'store/product_detail.html', context)

def search(request):
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            products = Product.objects.order_by('-created_date').filter(Q(description__icontains=keyword) | Q(product_name__icontains=keyword))
            product_count = products.count()

    context = {
        'products':products,
        'product_count': products.count,

    }
    return render(request, 'store/store.html', context)

templates/store/cart.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
{% if not cart_items %}

<h2 class="text-center"> Your shopping cart is empty. </h2>
<br>
<div class="text-center">
	<a href="{% url 'store'%}" class="btn btn-primary">Continue shopping </a>

</div>

{% else %}

<div class="row">
	<aside class="col-lg-9">
<div class="card">
<table class="table table-borderless table-shopping-cart">
<thead class="text-muted">
<tr class="small text-uppercase">
  <th scope="col">Product</th>
  <th scope="col" width="120">Quantity</th>
  <th scope="col" width="120">Price</th>
  <th scope="col" class="text-right" width="200"> </th>
</tr>
</thead>
<tbody>


{% for cart_item in cart_items %}

<tr>
	<td>
		<figure class="itemside align-items-center">
			<div class="aside"><img src="{{ cart_item.product.images.url}}" class="img-sm"></div>
			<figcaption class="info">
				<a href="{{ cart_item.product.get_url }}" class="title text-dark">{{ cart_item.product.product_name }}</a>
				<p class="text-muted small">
					{% if cart_item.variations.all %}
						{% for item in cart_item.variations.all %}
							{{ item.variation_category | capfirst}}: {{ item.variation_value | capfirst}} <br>

						{% endfor %}


					{% endif %}
				</p>
			</figcaption>
		</figure>
	</td>
	<td>
		<!-- col.// -->
					<div class="col">
						<div class="input-group input-spinner">
							<div class="input-group-prepend">
							<a href= "{% url 'remove_cart' cart_item.product.id cart_item.id %}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
							</div>
							<input type="text" class="form-control"  value="{{ cart_item.quantity }}">
							<div class="input-group-append">
								<form class="" action="{% url 'add_cart' cart_item.product.id %}" method="POST">
									{% csrf_token %}
									{% for item in cart_item.variations.all %}
										<input type="hidden" name="{{ item.variation_category |lower }}" value="{{ item.variation_value | capfirst }}">
									{% endfor %}
									<button class="btn btn-light" type="submit" id="button-minus"> <i class="fa fa-plus"></i> </button>
								</form>
							</div>
						</div> <!-- input-group.// -->
					</div> <!-- col.// -->
	</td>
	<td>
		<div class="price-wrap">
			<var class="price">₺ {{ cart_item.sub_total}} </var>
			<small class="text-muted"> ₺ {{ cart_item.product.price }} each </small>
		</div> <!-- price-wrap .// -->
	</td>
	<td class="text-right">
	<a href="{% url 'remove_cart_item' cart_item.product.id cart_item.id %}" onclick ="return confirm('Are you sure that you want to delete this item?')" class="btn btn-danger"> Remove</a>
	</td>
</tr>
{% endfor %}

</tbody>
</table>
</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<aside class="col-lg-3">

		<div class="card">
		<div class="card-body">
			<dl class="dlist-align">
			  <dt>Total price:</dt>
			  <dd class="text-right">₺{{total}}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Tax:</dt>
			  <dd class="text-right"> ₺{{tax}}</dd>
			</dl>
			<dl class="dlist-align">
			  <dt>Grand Total:</dt>
			  <dd class="text-right text-dark b"><strong>₺{{grand_total}}</strong></dd>
			</dl>
			<hr>
			<p class="text-center mb-3">
				<img src="{% static './images/misc/payments.png' %}" height="26">
			</p>
			<a href="./place-order.html" class="btn btn-primary btn-block"> Checkout </a>
			<a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
		</div> <!-- card-body.// -->
		</div> <!-- card.// -->

</aside> <!-- col.// -->


</div> <!-- row.// -->
{% endif %}
<!-- ============================ COMPONENT 1 END .// ================================= -->

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->


{% endblock %}

templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="section-content padding-y bg">
<div class="container">

<!-- ============================ COMPONENT 1 ================================= -->
<div class="card">
	<div class="row no-gutters">
		<aside class="col-md-6">
<article class="gallery-wrap">
	<div class="img-big-wrap">
	   <a href="#"><img src="{{single_product.images.url }}"></a>
	</div> <!-- img-big-wrap.// -->

</article> <!-- gallery-wrap .end// -->
		</aside>
		<main class="col-md-6 border-left">

			<form action="{% url 'add_cart' single_product.id %}" method="POST">
				{% csrf_token %}


			<article class="content-body">

			<h2 class="title">{{ single_product.product_name }}</h2>

			<div class="mb-3">
				<var class="price h4">₺ {{single_product.price}}</var>
			</div>

			<p>{{ single_product.description}}</p>


			<hr>
				<div class="row">
					<div class="item-option-select">
						<h6>Choose Color</h6>
							<select  name="color" class="form-control" required>
								<option value="" disabled selected > Select</option>
								{% for i in single_product.variation_set.colors %}
								<option value="{{ i.variation_value | lower }}">{{i.variation_value | capfirst }}</option>
								{% endfor %}

							</select>
					</div>
				</div> <!-- row.// -->

				<hr>
			  {% if single_product.stock <= 0 %}
			    <h5 class= "text-danger" >Out of Stock</h5>
			    {% else %}
				    <button type="submit"  class="btn  btn-primary"> <span class="text">Add to Cart</span> <i class="fas fa-shopping-cart"></i>  </button>
						
			    {% endif %}
			</article> <!-- product-info-aside .// -->
		</form>
		</main> <!-- col.// -->
	</div> <!-- row.// -->
</div> <!-- card.// -->
<!-- ============================ COMPONENT 1 END .// ================================= -->

<br>

<div class="row">
			<div class="col-md-9">

	<header class="section-heading">
		<h3>Customer Reviews </h3>

	</header>

	<article class="box mb-3">
		<div class="icontext w-100">
			<img src="{% static './images/avatars/avatar1.jpg' %}" class="img-xs icon rounded-circle">
			<div class="text">
				<span class="date text-muted float-md-right">07.04.2024 </span>
				<h6 class="mb-1">Aslıhan Kuzucu </h6>

			</div>
		</div> <!-- icontext.// -->
		<div class="mt-3">
			<p>
			Çok güzel bir araba, oğluma doğum günü hediyesi aldım.
			</p>
		</div>
	</article>



	</div> <!-- col.// -->
</div> <!-- row.// -->


</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->



{% endblock %}

templates/store/store.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
<div class="container">
	{% if 'search' in request.path %}
		<h2 class="title-page">Search Result</h2>
	{% else %}
		<h2 class="title-page">Our Store</h2>
	{% endif %}

</div> <!-- container //  -->
</section>
<!-- ========================= SECTION INTRO END// ========================= -->
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
<div class="container">

<div class="row">
	<aside class="col-md-3">

<div class="card">
	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Categories</h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_1" style="">
			<div class="card-body">

				<ul class="list-menu">
					<li><a href="{%url 'store' %}">All Products </a></li>
					{% for category in links %}
				<li><a href="{{ category.get_url }}">{{ category.category_name }}</a></li>
					{% endfor %}

				</ul>

			</div> <!-- card-body.// -->
		</div>
	</article> <!-- filter-group  .// -->


	<article class="filter-group">
		<header class="card-header">
			<a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true" class="">
				<i class="icon-control fa fa-chevron-down"></i>
				<h6 class="title">Price range </h6>
			</a>
		</header>
		<div class="filter-content collapse show" id="collapse_3" style="">
			<div class="card-body">

				<div class="form-row">
				<div class="form-group col-md-6">
				  <label>Min</label>
				  <!-- <input class="form-control" placeholder="$0" type="number"> -->
				  	<select class="mr-2 form-control">
						<option value="0">₺0</option>
						<option value="50">₺50</option>
						<option value="100">₺100</option>
						<option value="150">₺150</option>
						<option value="200">₺200</option>
						<option value="500">₺500</option>
						<option value="1000">₺1000</option>
					</select>
				</div>
				<div class="form-group text-right col-md-6">
				  <label>Max</label>
				  	<select class="mr-2 form-control">
						<option value="50">₺50</option>
						<option value="100">₺100</option>
						<option value="150">₺150</option>
						<option value="200">₺200</option>
						<option value="500">₺500</option>
						<option value="1000">₺1000</option>
						<option value="2000">₺2000+</option>
					</select>
				</div>
				</div> <!-- form-row.// -->
				<button class="btn btn-block btn-primary">Apply</button>
			</div><!-- card-body.// -->
		</div>
	</article> <!-- filter-group .// -->

</div> <!-- card.// -->

	</aside> <!-- col.// -->
	<main class="col-md-9">

<header class="border-bottom mb-4 pb-3">
		<div class="form-inline">
			<span class="mr-md-auto"><b>{{ product_count}}</b> items found </span>

		</div>
</header><!-- sect-heading -->

<div class="row">
	{% if products %}
	{% for product in products %}
	<div class="col-md-4">
		<figure class="card card-product-grid">
			<div class="img-wrap">

			<a href="{{ product.get_url }}"><img src="{{ product.images.url }}"></a>


			</div> <!-- img-wrap.// -->
			<figcaption class="info-wrap">
				<div class="fix-height">
					<a href="{{ product.get_url }}" class="title">{{ product.product_name}}</a>
					<div class="price-wrap mt-2">
						<span class="price">₺ {{ product.price }}</span>

					</div> <!-- price-wrap.// -->
				</div>
				<a href="{{ product.get_url }}" class="btn btn-block btn-primary">View Details </a>
			</figcaption>
		</figure>
	</div> <!-- col.// -->
	{% endfor %}
	{% else %}
	<div>
		<h2>No result found. Please try again. </h2>
	</div>
	{% endif %}
</div> <!-- row end.// -->


<nav class="mt-4" aria-label="Page navigation sample">
{% if products.has_other_pages %}
  <ul class="pagination">
		{% if products.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{products.previous_page_number}}">Previous</a></li>
		{% else %}
		<li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
		{% endif %}

		{% for i in products.paginator.page_range %}
			{% if products.number == i %}
    		<li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
			{% else %}
				<li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
			{% endif %}
  	{% endfor%}

		{% if products.has_next %}
    	<li class="page-item"><a class="page-link" href="?page={{products.next_page_number}}">Next</a></li>
		{% else %}
			<li class="page-item disabled "><a class="page-link" href="#">Next</a></li>
		{% endif %}
  </ul>
{% endif %}
</nav>

	</main> <!-- col.// -->

</div>

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}